import '~/styles/globals.css'

import { type Metadata } from 'next'
import { Fira_Code } from 'next/font/google'

import { TRPCReactProvider } from '~/trpc/react'

import { Toaster } from './_components/Toaster'

export const metadata: Metadata = {
  title: 'Rail Manager v2',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const fira = Fira_Code({
  subsets: ['latin'],
  variable: '--font-fira-code-mono',
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fira.className}`}>
      <body className="dotted-bg min-h-screen">
        <Toaster />

        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  )
}
